import { DurationInput } from '../common/DurationInput';
import { TimeInput } from '../common/TimeInput';

export type PlannedWorkdayForm = { clockIn: string; clockOut: string; stopMinutes: string };
export type TodayFormState = { weeklyRemaining: string; clockIn: string; todayClockOut: string; todayStopMinutes: string; fridayClockIn: string; fridayStopMinutes: string; remainingDayPlans: Record<string, PlannedWorkdayForm> };

const weekdayLabels: Record<number, string> = { 1: '월', 2: '화', 3: '수', 4: '목' };
const defaultPlan: PlannedWorkdayForm = { clockIn: '09:00', clockOut: '18:00', stopMinutes: '0' };

function StopMinutesInput(props: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="grid min-w-0 gap-2 text-sm font-semibold text-slate-700"><span>{props.label}</span><div className="flex min-w-0 items-center gap-1 rounded-2xl border border-slate-200 bg-white px-2 py-3 focus-within:border-brand"><input inputMode="numeric" value={props.value} onChange={(event) => props.onChange(event.target.value.replace(/\D/g, ''))} className="min-w-0 flex-1 bg-transparent text-base outline-none" /><span className="text-xs font-bold text-slate-400">분</span></div></label>;
}

export function TodayCalculatorForm({ value, onChange, planningWeekdays, getDefaultTodayClockOut }: { value: TodayFormState; onChange: (value: TodayFormState) => void; planningWeekdays: number[]; getDefaultTodayClockOut: (clockIn: string, stopMinutes: string) => string }) {
  const updatePlan = (weekday: number, plan: PlannedWorkdayForm) => onChange({ ...value, remainingDayPlans: { ...value.remainingDayPlans, [weekday]: plan } });

  return <div className="grid gap-4"><DurationInput label="Flex 상 이번 주 남은 근무시간" value={value.weeklyRemaining} onChange={(weeklyRemaining) => onChange({ ...value, weeklyRemaining })} hint="예: 07:40 또는 740 → 7시간 40분" /><div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_5rem] gap-2"><TimeInput label="오늘 출근" value={value.clockIn} onChange={(clockIn) => onChange({ ...value, clockIn, todayClockOut: getDefaultTodayClockOut(clockIn, value.todayStopMinutes) })} /><TimeInput label="오늘 퇴근" value={value.todayClockOut} onChange={(todayClockOut) => onChange({ ...value, todayClockOut })} /><StopMinutesInput label="업무정지" value={value.todayStopMinutes} onChange={(todayStopMinutes) => onChange({ ...value, todayStopMinutes, todayClockOut: getDefaultTodayClockOut(value.clockIn, todayStopMinutes) })} /></div>{planningWeekdays.length > 0 && <div className="grid gap-3 rounded-3xl bg-slate-50 p-4"><div><p className="text-sm font-black text-slate-700">금요일 전 근무 계획</p><p className="mt-1 text-xs font-medium leading-5 text-slate-500">식사/법정 휴게는 자동 반영돼요. 추가 자리비움은 업무정지 분으로 입력하고 기본값은 0분이에요.</p></div>{planningWeekdays.map((weekday) => { const plan = value.remainingDayPlans[weekday] ?? defaultPlan; return <div key={weekday} className="grid grid-cols-[1.25rem_minmax(0,1fr)_minmax(0,1fr)_5rem] items-end gap-2"><div className="pb-3 text-sm font-black text-slate-600">{weekdayLabels[weekday]}</div><TimeInput label="출근" value={plan.clockIn} onChange={(clockIn) => updatePlan(weekday, { ...plan, clockIn })} /><TimeInput label="퇴근" value={plan.clockOut} onChange={(clockOut) => updatePlan(weekday, { ...plan, clockOut })} /><StopMinutesInput label="정지" value={plan.stopMinutes} onChange={(stopMinutes) => updatePlan(weekday, { ...plan, stopMinutes })} /></div>; })}</div>}<div className="grid grid-cols-[minmax(0,1fr)_5rem] gap-2"><TimeInput label="금요일 예상 출근 시간" value={value.fridayClockIn} onChange={(fridayClockIn) => onChange({ ...value, fridayClockIn })} /><StopMinutesInput label="업무정지" value={value.fridayStopMinutes} onChange={(fridayStopMinutes) => onChange({ ...value, fridayStopMinutes })} /></div></div>;
}
