import { AlertTriangle } from 'lucide-react';
import { Card } from '../common/Card';
import { Badge } from '../common/Badge';
import { formatDuration } from '../../lib/time/duration';
import { formatTime } from '../../lib/time/formatTime';
import type { CoreTimeValidationResult, Minutes } from '../../types/work';
import type { TimeEntryValidationResult } from '../../lib/work/validateTimeEntry';
import { CoreTimeWarning } from './CoreTimeWarning';

export function TodayResultCard(props: { targetLabel: string; currentTime: Minutes; earliestClockOut: Minutes | null; recognizedSoFar: number; realtimeRemaining: number; targetRequiredMinutes: number; plannedDayCount: number; plannedBeforeFridayMinutes: number; excessBeforeFridayMinutes: number; projectedExcessMinutes: number; entryWarnings: { label: string; result: TimeEntryValidationResult }[]; core: CoreTimeValidationResult; isImpossible: boolean }) {
  return <Card className="bg-gradient-to-br from-brand to-violet-500 text-white"><div className="flex items-start justify-between gap-2"><p className="text-sm font-bold opacity-80">{props.targetLabel} 계산 결과</p><div className="text-right"><Badge tone={props.isImpossible ? 'warn' : 'good'}>{props.isImpossible ? '22:00 초과' : '계산 완료'}</Badge><p className="mt-2 text-xs font-bold opacity-75">현재 시간 {formatTime(props.currentTime)}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-3xl bg-white/15 p-4"><p className="text-sm font-bold opacity-80">실시간 잔여</p><div className="mt-2 text-4xl font-black tracking-tight">{formatDuration(Math.max(0, props.realtimeRemaining))}</div></div><div className="rounded-3xl bg-white/15 p-4"><p className="text-sm font-bold opacity-80">{props.targetLabel} 퇴근</p><div className="mt-2 text-4xl font-black tracking-tight">{props.earliestClockOut == null ? '--:--' : formatTime(props.earliestClockOut)}</div></div></div>{props.isImpossible && <div className="mt-4 flex gap-2 rounded-2xl bg-white/15 p-3 text-sm font-bold"><AlertTriangle size={18} />업무 가능 시간 안에 달성하기 어려워요.</div>}<div className="mt-6 grid gap-2 rounded-3xl bg-white p-4 text-ink"><div className="flex justify-between"><span>오늘 실시간 근무 현황</span><strong>{formatDuration(props.recognizedSoFar)}</strong></div>{props.plannedDayCount > 0 && <div className="flex justify-between"><span>금요일 전 계획 반영</span><strong>{formatDuration(props.plannedBeforeFridayMinutes)}</strong></div>}{props.excessBeforeFridayMinutes > 0 && <div className="flex justify-between text-emerald-600"><span>금요일 전 초과 예정</span><strong>{formatDuration(props.excessBeforeFridayMinutes)}</strong></div>}<div className="flex justify-between"><span>{props.targetLabel} 필요 근무</span><strong>{formatDuration(Math.max(0, props.targetRequiredMinutes))}</strong></div>{props.projectedExcessMinutes > 0 && <div className="flex justify-between text-emerald-600"><span>퇴근 시점 예상 초과</span><strong>{formatDuration(props.projectedExcessMinutes)}</strong></div>}{props.entryWarnings.map((warning) => <div key={`${warning.label}-${warning.result.reason}`} className="flex gap-2 rounded-2xl bg-amber-50 p-3 text-sm font-bold text-amber-700"><AlertTriangle size={18} /><span>{warning.label}: {warning.result.reason}</span></div>)}<CoreTimeWarning result={props.core} /></div></Card>;
}
