import { DurationInput } from '../common/DurationInput';
import { TimeInput } from '../common/TimeInput';

export type PlannedWorkdayForm = { clockIn: string; clockOut: string; breakMinutes: string };
export type TodayFormState = { weeklyRemaining: string; clockIn: string; todayClockOut: string; todayBreakMinutes: string; fridayClockIn: string; fridayBreakMinutes: string; remainingDayPlans: Record<string, PlannedWorkdayForm> };

const weekdayLabels: Record<number, string> = { 1: '월', 2: '화', 3: '수', 4: '목' };
const defaultPlan: PlannedWorkdayForm = { clockIn: '09:00', clockOut: '18:00', breakMinutes: '0' };

function BreakMinutesInput(props: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="grid min-w-0 gap-2 text-sm font-semibold text-slate-700"><span>{props.label}</span><div className="flex min-w-0 items-center gap-1 rounded-2xl border border-slate-200 bg-white px-3 py-3 focus-within:border-brand"><input inputMode="numeric" value={props.value} onChange={(event) => props.onChange(event.target.value.replace(/\D/g, ''))} className="min-w-0 flex-1 bg-transparent text-base outline-none" /><span className="text-xs font-bold text-slate-400">분</span></div></label>;
}

export function TodayCalculatorForm({ value, onChange, planningWeekdays, getDefaultTodayClockOut }: { value: TodayFormState; onChange: (value: TodayFormState) => void; planningWeekdays: number[]; getDefaultTodayClockOut: (clockIn: string, breakMinutes: string) => string }) {
  const updatePlan = (weekday: number, plan: PlannedWorkdayForm) => onChange({ ...value, remainingDayPlans: { ...value.remainingDayPlans, [weekday]: plan } });

  return <div className="grid gap-4"><DurationInput label="Flex 상 이번 주 남은 근무시간" value={value.weeklyRemaining} onChange={(weeklyRemaining) => onChange({ ...value, weeklyRemaining })} hint="예: 07:40 또는 740 → 7시간 40분" /><div className="grid grid-cols-2 gap-3"><TimeInput label="오늘 출근" value={value.clockIn} onChange={(clockIn) => onChange({ ...value, clockIn, todayClockOut: getDefaultTodayClockOut(clockIn, value.todayBreakMinutes) })} /><TimeInput label="오늘 퇴근" value={value.todayClockOut} onChange={(todayClockOut) => onChange({ ...value, todayClockOut })} /></div><BreakMinutesInput label="오늘 휴게시간" value={value.todayBreakMinutes} onChange={(todayBreakMinutes) => onChange({ ...value, todayBreakMinutes, todayClockOut: getDefaultTodayClockOut(value.clockIn, todayBreakMinutes) })} />{planningWeekdays.length > 0 && <div className="grid gap-3 rounded-3xl bg-slate-50 p-4"><div><p className="text-sm font-black text-slate-700">금요일 전 근무 계획</p><p className="mt-1 text-xs font-medium leading-5 text-slate-500">내일부터 목요일까지 표시돼요. 휴게시간은 각 요일별 분 단위로 반영하며 기본값은 0분이에요.</p></div>{planningWeekdays.map((weekday) => { const plan = value.remainingDayPlans[weekday] ?? defaultPlan; return <div key={weekday} className="grid grid-cols-[1.5rem_minmax(0,1fr)_minmax(0,1fr)] items-end gap-2"><div className="pb-3 text-sm font-black text-slate-600">{weekdayLabels[weekday]}</div><TimeInput label="출근" value={plan.clockIn} onChange={(clockIn) => updatePlan(weekday, { ...plan, clockIn })} /><TimeInput label="퇴근" value={plan.clockOut} onChange={(clockOut) => updatePlan(weekday, { ...plan, clockOut })} /><div /><div className="col-span-2"><BreakMinutesInput label="휴게시간" value={plan.breakMinutes} onChange={(breakMinutes) => updatePlan(weekday, { ...plan, breakMinutes })} /></div></div>; })}</div>}<TimeInput label="금요일 예상 출근 시간" value={value.fridayClockIn} onChange={(fridayClockIn) => onChange({ ...value, fridayClockIn })} /><BreakMinutesInput label="금요일 휴게시간" value={value.fridayBreakMinutes} onChange={(fridayBreakMinutes) => onChange({ ...value, fridayBreakMinutes })} /></div>;
}
